### ISSUE TITLE
OSError(errno.ENOENT)

### ISSUE THREAD

**Issue by faveoled** [flathub-infra/flatpak-builder-lint#263]
```
user@hp-laptop:~/Dev/Flatpak/flathub$ flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions repo repo
Traceback (most recent call last):
  File "/app/bin/flatpak-builder-lint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/cli.py", line 158, in main
    if results := run_checks(args.type, path, args.exceptions, args.appid):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/cli.py", line 70, in run_checks
    check_method(check_method_arg)
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/checks/appid.py", line 49, in check_repo
    metadata = ostree.get_metadata(path, self.repo_primary_ref)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/ostree.py", line 57, in get_metadata
    ref = get_primary_ref(repo)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/ostree.py", line 33, in get_primary_ref
    refs_cmd = cli(repo, "refs", "--list")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/ostree.py", line 18, in cli
    raise OSError(errno.ENOENT)
OSError: 2

```
Any ideas? Not clear what the problem is

**Comment by faveoled** [comment]
Thanks. that's clear now. But the user experience really needs some work

**Comment by bbhtt** [comment]
It should've been easier if you followed the documentation. That has every command needed to be able to perform the checks.

I opened a PR to add a message.
